### ISSUE TITLE
Возник вопрос при выполнении задания (Сам код работает верно)!

### ISSUE THREAD

**Issue by camenzindmp** [camenzindmp/Modernization#1]
## Краткое описание ###

Несмотря на то, что код работает корректно и в целом мне понятен, возник небольшой вопрос логике его работы.

## Шаги для воспроизведения: ##

1. Скопировать содержимое файлов **Main.java** и **BonusMilesService.java** из этого репозитория
2. Создать в **IDE** класс **Main** и вставить в него скопированное содержимое из **Main.java**
3. Создать в **IDE** класс **BonusMilesService** и вставить в него скопированное содержимое из **BonusMilesService**
4. Убедиться в корректной работе кода 

## Ожидаемый и фактический результат: ## 
Совпадают, т.к. код работает верно

## Непосредственно вопрос: ##

Содержимое переменной ```cost``` из строки  ```public int calculate (int cost)``` в методе ```BonusMilesService.java```(*см. скриншот №1*), насколько я понимаю, берется из класса ```Main.java``` и соответствует значению в переменной ```price``` типа ```int```(*скриншот №2*); **Это верно??**

*Скриншот №1*
![impq](https://user-images.githubusercontent.com/59551106/75146443-db7dbf80-5746-11ea-9f98-39d25aebdba8.png)

*Скриншот №2*
![impq2](https://user-images.githubusercontent.com/59551106/75146448-df114680-5746-11ea-8d57-07476fea0073.png)

-----------------------------------------------------------------------------------------

Если это верно, то правильно ли я понимаю, что строкой ```public int calculate (int cost)``` мы как бы **объявляем** переменную и **cразу же присваиваем ей значение** из ```Main.java```?? *(Сделал такой вывод, проходя программу пошагово в режиме отладки - см. скриншот №3)*

*Скриншот №3*
![impq5](https://user-images.githubusercontent.com/59551106/75146737-6b236e00-5747-11ea-8348-f66a4ac74c7f.png)

-----------------------------------------------------------------------------------------

## Иначе говоря... ##

Иначе говоря, мне не совсем понятно, **как IDE понимает, что ```cost``` = ```price```...**

-----------------------------------------------------------------------------------------

*Вопрос не возник во время лекции, т.к. на лекции переменные в обоих классах как раз назывались одинаково ```amount```:*

![impq3](https://user-images.githubusercontent.com/59551106/75145543-d9b2fc80-5744-11ea-8d84-8b3dcb5ff8c0.png)

![impq4](https://user-images.githubusercontent.com/59551106/75145555-e0417400-5744-11ea-89d5-1190b75612e9.png)

## Окружение ## 
* Версия ОС: Windows 10 x64
* Версия Java: openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

**Comment by coursar** [comment]
Не совсем так, благодаря тому, что вы делаете:
```java
// 5-ая строка Main.java
int miles = service.calculate(price);
```
Это превращается в:
```java
int miles = service.calculate(10_000);
```

Затем Java смотрит на метод `calculate` и видит там следующее:
```
// BonusMilesService.java
public int calculate(int cost) {
  ...
}
```

И буквально "кладёт" в параметр `cost` значение 10_000, т.е. можно представить вот так (не валидный Java-код):
```
// BonusMilesService.java
public int calculate(int cost = 10_000) {
  ...
}
```

Это работает только когда вы вызываете: `service.calculate(10_000)`. Когда вызовете `service.calculate(20_000)`, то Java сделает:
```
// BonusMilesService.java
public int calculate(int cost = 20_000) {
  ...
}
```

IDEA понимает, кому и что передавать исходя из позиций и типов:
`service.calculate(10_000)` - в круглых скобках один аргумент типа `int` и он первый по счёту, `public int calculate(int cost)` - в круглых скобках один аргумент типа `int` и он первый по счёту. Поэтому и получится `cost = 10_000`.
